classic: false

blocks:
  - permission
  - user
  - group
  - size
  - date
  - name

color:
  when: auto
  theme: custom

date: date

dereference: false

display: almost-all

icons:
  when: never

indicators: false

layout: grid

recursion:
  enabled: false

size: default

sorting:
  column: name
  reverse: false
  dir-grouping: first

no-symlink: false

total-size: false

symlink-arrow: →
